name: MediData
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.17.1
  auto_size_text: ^3.0.0
  chat_gpt_sdk: ^3.1.6
  dash_chat_2: ^0.0.21
  url_launcher: ^6.3.2
  flutter_native_splash: ^2.4.8
  dio: ^5.11.0
  path_provider: ^2.1.6
  open_filex: ^4.7.0
  http: ^1.5.0
  file_picker: ^12.0.0
  shared_preferences: ^2.5.5
  just_audio: ^0.10.6
  video_player: ^2.14.0
  audio_service: ^0.18.19
  audio_session: ^0.2.4
  fl_chart: ^1.2.0
  firebase_messaging: ^16.6.0
  firebase_core: ^4.14.0
  flutter_local_notifications: ^22.3.0
  connectivity_plus: ^7.3.1
  flutter_markdown_plus: ^1.0.12
  google_fonts: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/icon-1.png"

flutter:
  uses-material-design: true
  assets:
    - images/
